---
title: "Covid-19 State-level Trends"
output: html_notebook
---

```{r include=F}
library(dplyr)
library(tidyr)
library(data.table)
library(ggplot2)
library(tidyquant)
library(ggthemes)
```

Start with the .csv file compiled by NY Times...because it's pretty easy to work with. In this case, I'm going to save a stable copy of the data. 

```{r}
source('data/data-get.R')
read.csv('data/us-states.csv')
```

In this data frame the deaths and cases are cumulative...so we can compute daily new cases and daily new deaths using the change in the original variables.

```{r}
covid.states <- tbl_df(covid.states) %>% mutate(date=as.Date(date)) %>% 
                 group_by(state) %>% arrange(state,date) %>% 
                 mutate(daily_new_case=cases-lag(cases),
                        daily_new_death=deaths-lag(deaths))

# there is no 0 day in the data frame so we need to fix the first observation for each day
covid.states <- covid.states %>% group_by(state) %>% arrange(state,date) %>%
                 mutate(daily_new_case=ifelse(row_number()==1,cases,daily_new_case),
                        daily_new_death=ifelse(row_number()==1,deaths,daily_new_death))
  
head(covid.states)
```

```{r}
# calculate the ema
#covid.states <- covid.states %>% group_by(state) %>% arrange(state,date) %>% 
   
```

A few randomly chosen states with smoothed death counts 

```{r}
# Upper Midwest
umw <- covid.states %>% filter(state %in% c("Michigan","Ohio","Indiana","Wisconsin","Minnesota","Iowa","Illinois"))

wc <- covid.states %>% filter(state %in% c("California","Oregon","Washington"))
sw <- covid.states %>% filter(state %in% c("Texas","New Mexico","Arizona"))
  
ggplot(subset(umw,state=="Ohio"),aes(x=date,y=daily_new_death))+ geom_point() + geom_line() +
  geom_ma(ma_fun = EMA, n = 14) + theme_fivethirtyeight()

ggplot(subset(wc,state=="California"),aes(x=date,y=daily_new_death))+ geom_point() + geom_line() +
  geom_ma(ma_fun = EMA, n = 14) + theme_fivethirtyeight()

ggplot(subset(sw,state=="Texas"),aes(x=date,y=daily_new_case))+ geom_point() + geom_line() +
  geom_ma(ma_fun = EMA, n = 14) + theme_fivethirtyeight()

```


```{r}
# smoothed deaths moved forward in time 14 days from the smoothed cases series
plot.df <- covid.states %>% group_by(state) %>% 
            arrange(state,date) %>% 
             mutate(cases.L14=lag(daily_new_case,14))

ggplot(plot.df[plot.df$state=="Texas",],aes(x=log(cases.L14),y=log(daily_new_death))) + geom_point() 

```
